---
- name: get rpm file for minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: /opt/minikube.rpm

- name: Install rpm from file
  yum:
    name: /opt/minikube.rpm
    state: present
    disable_gpg_check: true # don't judge me

- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "nsimpson ALL=(ALL) NOPASSWD: /usr/bin/podman"
    validate: /usr/sbin/visudo -cf %s